name = "naymmmm/ai"
version = "0.1.0"
description = "A simple package for interfacing with the Google Cloud Vertex AI API"
authors = ["naymmmm"]
repository = "https://github.com/Naymmmm/ai.luau.git"
license = "MIT"

[target]
environment = "luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
